import streamlit as st

DB = "PRODUCT_WHEEL_OPT"
ATOMIC = f"{DB}.ATOMIC"
DATA_MART = f"{DB}.DATA_MART"

QUERY_SCENARIOS = f"""
SELECT DISTINCT SCENARIO_ID
FROM {DATA_MART}.FACT_LINE_SCHEDULE_OPTIMIZED
ORDER BY SCENARIO_ID DESC
"""

QUERY_KPI_BY_SCENARIO = f"""
SELECT *
FROM {DATA_MART}.FACT_SERVICE_AND_SCHEDULE_KPI
WHERE SCENARIO_ID = '{{scenario}}'
"""

QUERY_SCHEDULE_BY_SCENARIO = f"""
SELECT s.SCENARIO_ID, s.LINE_ID, l.LINE_CODE, pl.PLANT_NAME,
       s.TIME_SLOT_START, s.TIME_SLOT_END,
       s.PRODUCT_ID, p.PRODUCT_CODE, p.PRODUCT_DESCRIPTION, p.PRODUCT_FAMILY,
       s.PLANNED_QTY, s.PROJECTED_FILL_RATE, s.PROJECTED_INVENTORY_QTY,
       s.TOTAL_CHANGEOVER_TIME_HOURS, s.OBJECTIVE_COST
FROM {DATA_MART}.FACT_LINE_SCHEDULE_OPTIMIZED s
JOIN {ATOMIC}.DIM_PRODUCTION_LINE l ON s.LINE_ID = l.LINE_ID
JOIN {ATOMIC}.DIM_PLANT pl ON l.PLANT_ID = pl.PLANT_ID
JOIN {ATOMIC}.DIM_PRODUCT p ON s.PRODUCT_ID = p.PRODUCT_ID
WHERE s.SCENARIO_ID = '{{scenario}}'
ORDER BY l.LINE_CODE, s.TIME_SLOT_START
"""

QUERY_ENRICHED_FORECAST = f"""
SELECT e.*, p.PRODUCT_CODE, p.PRODUCT_FAMILY, c.CUSTOMER_NAME
FROM {DATA_MART}.FACT_DEMAND_FORECAST_ENRICHED e
JOIN {ATOMIC}.DIM_PRODUCT p ON e.PRODUCT_ID = p.PRODUCT_ID
JOIN {ATOMIC}.DIM_CUSTOMER c ON e.CUSTOMER_ID = c.CUSTOMER_ID
"""

QUERY_PLANTS = f"SELECT * FROM {ATOMIC}.DIM_PLANT ORDER BY PLANT_NAME"

QUERY_LINES_BY_PLANT = f"""
SELECT l.*, p.PLANT_NAME
FROM {ATOMIC}.DIM_PRODUCTION_LINE l
JOIN {ATOMIC}.DIM_PLANT p ON l.PLANT_ID = p.PLANT_ID
ORDER BY p.PLANT_NAME, l.LINE_CODE
"""

QUERY_PRODUCTS = f"SELECT * FROM {ATOMIC}.DIM_PRODUCT ORDER BY PRODUCT_FAMILY, PRODUCT_CODE"

QUERY_DEMAND_LANDSCAPE = f"""
SELECT c.CUSTOMER_NAME, p.PRODUCT_FAMILY, SUM(d.FORECAST_QTY) AS TOTAL_FORECAST_QTY
FROM {ATOMIC}.FACT_DEMAND_FORECAST d
JOIN {ATOMIC}.DIM_PRODUCT p ON d.PRODUCT_ID = p.PRODUCT_ID
JOIN {ATOMIC}.DIM_CUSTOMER c ON d.CUSTOMER_ID = c.CUSTOMER_ID
GROUP BY c.CUSTOMER_NAME, p.PRODUCT_FAMILY
ORDER BY c.CUSTOMER_NAME, p.PRODUCT_FAMILY
"""

QUERY_DEMAND_TIMESERIES = f"""
SELECT d.FORECAST_WEEK_START, p.PRODUCT_FAMILY, SUM(d.FORECAST_QTY) AS FORECAST_QTY
FROM {ATOMIC}.FACT_DEMAND_FORECAST d
JOIN {ATOMIC}.DIM_PRODUCT p ON d.PRODUCT_ID = p.PRODUCT_ID
GROUP BY d.FORECAST_WEEK_START, p.PRODUCT_FAMILY
ORDER BY d.FORECAST_WEEK_START, p.PRODUCT_FAMILY
"""

QUERY_LINE_CAPABILITIES = f"""
SELECT l.LINE_ID, l.LINE_CODE, l.LINE_NAME, l.LINE_TYPE,
       l.IS_ALLERGEN_DEDICATED_FLAG, p.PLANT_NAME,
       COUNT(DISTINCT t.PRODUCT_ID) AS PRODUCT_COUNT,
       AVG(t.RUN_RATE_UNITS_PER_HOUR) AS AVG_RUN_RATE,
       MIN(t.RUN_RATE_UNITS_PER_HOUR) AS MIN_RUN_RATE,
       MAX(t.RUN_RATE_UNITS_PER_HOUR) AS MAX_RUN_RATE
FROM {ATOMIC}.DIM_PRODUCTION_LINE l
JOIN {ATOMIC}.DIM_PLANT p ON l.PLANT_ID = p.PLANT_ID
LEFT JOIN {ATOMIC}.FACT_LINE_PRODUCT_THROUGHPUT t ON l.LINE_ID = t.LINE_ID
GROUP BY l.LINE_ID, l.LINE_CODE, l.LINE_NAME, l.LINE_TYPE,
         l.IS_ALLERGEN_DEDICATED_FLAG, p.PLANT_NAME
ORDER BY p.PLANT_NAME, l.LINE_CODE
"""

QUERY_THROUGHPUT_DETAIL = f"""
SELECT l.LINE_CODE, t.RUN_RATE_UNITS_PER_HOUR
FROM {ATOMIC}.FACT_LINE_PRODUCT_THROUGHPUT t
JOIN {ATOMIC}.DIM_PRODUCTION_LINE l ON t.LINE_ID = l.LINE_ID
"""

QUERY_CALENDAR_GRID = f"""
SELECT l.LINE_CODE, DATE(c.TIME_SLOT_START) AS SLOT_DATE,
       c.CALENDAR_STATUS, COUNT(*) AS SLOT_COUNT
FROM {ATOMIC}.FACT_LINE_CALENDAR c
JOIN {ATOMIC}.DIM_PRODUCTION_LINE l ON c.LINE_ID = l.LINE_ID
GROUP BY l.LINE_CODE, DATE(c.TIME_SLOT_START), c.CALENDAR_STATUS
ORDER BY l.LINE_CODE, SLOT_DATE
"""

QUERY_CHANGEOVER_MATRIX = f"""
SELECT co.LINE_ID, l.LINE_CODE,
       pf.PRODUCT_CODE AS FROM_PRODUCT, pt.PRODUCT_CODE AS TO_PRODUCT,
       co.CHANGEOVER_TIME_HOURS, co.CHANGEOVER_COST
FROM {ATOMIC}.FACT_LINE_PRODUCT_CHANGEOVER co
JOIN {ATOMIC}.DIM_PRODUCTION_LINE l ON co.LINE_ID = l.LINE_ID
JOIN {ATOMIC}.DIM_PRODUCT pf ON co.FROM_PRODUCT_ID = pf.PRODUCT_ID
JOIN {ATOMIC}.DIM_PRODUCT pt ON co.TO_PRODUCT_ID = pt.PRODUCT_ID
WHERE co.LINE_ID = {{line_id}}
ORDER BY pf.PRODUCT_CODE, pt.PRODUCT_CODE
"""

QUERY_INVENTORY_SNAPSHOT = f"""
SELECT p.PRODUCT_ID, p.PRODUCT_CODE, p.PRODUCT_FAMILY,
       pl.PLANT_NAME,
       i.ON_HAND_QTY, i.SAFETY_STOCK_QTY, i.ON_ORDER_QTY,
       i.SNAPSHOT_TIMESTAMP
FROM {ATOMIC}.FACT_INVENTORY_POSITION i
JOIN {ATOMIC}.DIM_PRODUCT p ON i.PRODUCT_ID = p.PRODUCT_ID
JOIN {ATOMIC}.DIM_PLANT pl ON i.PLANT_ID = pl.PLANT_ID
QUALIFY ROW_NUMBER() OVER (PARTITION BY i.PRODUCT_ID, i.PLANT_ID ORDER BY i.SNAPSHOT_TIMESTAMP DESC) = 1
ORDER BY p.PRODUCT_FAMILY, p.PRODUCT_CODE
"""

QUERY_CONTRACTS = f"""
SELECT fc.CONTRACT_ID, fc.CUSTOMER_ID, c.CUSTOMER_NAME, c.CUSTOMER_SEGMENT,
       fc.CONTRACT_START_DATE, fc.CONTRACT_END_DATE,
       fc.SERVICE_LEVEL_TARGET_FILL_RATE, fc.MAX_DAYS_OF_SUPPLY_TARGET,
       COUNT(ci.CONTRACT_ITEM_ID) AS ITEM_COUNT,
       SUM(ci.MIN_ANNUAL_VOLUME) AS TOTAL_MIN_VOLUME
FROM {ATOMIC}.FACT_CONTRACT fc
JOIN {ATOMIC}.DIM_CUSTOMER c ON fc.CUSTOMER_ID = c.CUSTOMER_ID
LEFT JOIN {ATOMIC}.FACT_CONTRACT_ITEM ci ON fc.CONTRACT_ID = ci.CONTRACT_ID
GROUP BY fc.CONTRACT_ID, fc.CUSTOMER_ID, c.CUSTOMER_NAME, c.CUSTOMER_SEGMENT,
         fc.CONTRACT_START_DATE, fc.CONTRACT_END_DATE,
         fc.SERVICE_LEVEL_TARGET_FILL_RATE, fc.MAX_DAYS_OF_SUPPLY_TARGET
ORDER BY c.CUSTOMER_NAME
"""

QUERY_CONTRACT_ITEMS = f"""
SELECT ci.*, p.PRODUCT_CODE, p.PRODUCT_FAMILY, p.PRODUCT_DESCRIPTION
FROM {ATOMIC}.FACT_CONTRACT_ITEM ci
JOIN {ATOMIC}.DIM_PRODUCT p ON ci.PRODUCT_ID = p.PRODUCT_ID
WHERE ci.CONTRACT_ID = {{contract_id}}
ORDER BY p.PRODUCT_FAMILY, p.PRODUCT_CODE
"""

QUERY_CONTRACT_COMPLIANCE = f"""
WITH contract_products AS (
    SELECT fc.CUSTOMER_ID, fc.SERVICE_LEVEL_TARGET_FILL_RATE,
           fc.MAX_DAYS_OF_SUPPLY_TARGET, ci.PRODUCT_ID
    FROM {ATOMIC}.FACT_CONTRACT fc
    JOIN {ATOMIC}.FACT_CONTRACT_ITEM ci ON fc.CONTRACT_ID = ci.CONTRACT_ID
),
demand AS (
    SELECT cp.CUSTOMER_ID, cp.SERVICE_LEVEL_TARGET_FILL_RATE,
           cp.MAX_DAYS_OF_SUPPLY_TARGET,
           SUM(df.FORECAST_QTY) AS TOTAL_DEMAND
    FROM contract_products cp
    JOIN {ATOMIC}.FACT_DEMAND_FORECAST df
        ON cp.CUSTOMER_ID = df.CUSTOMER_ID AND cp.PRODUCT_ID = df.PRODUCT_ID
    GROUP BY cp.CUSTOMER_ID, cp.SERVICE_LEVEL_TARGET_FILL_RATE,
             cp.MAX_DAYS_OF_SUPPLY_TARGET
),
production AS (
    SELECT cp.CUSTOMER_ID,
           SUM(s.PLANNED_QTY) AS TOTAL_PLANNED
    FROM contract_products cp
    JOIN {DATA_MART}.FACT_LINE_SCHEDULE_OPTIMIZED s
        ON cp.PRODUCT_ID = s.PRODUCT_ID AND s.SCENARIO_ID = '{{scenario}}'
    GROUP BY cp.CUSTOMER_ID
)
SELECT d.CUSTOMER_ID, c.CUSTOMER_NAME,
       d.SERVICE_LEVEL_TARGET_FILL_RATE AS SLA_TARGET,
       d.MAX_DAYS_OF_SUPPLY_TARGET,
       COALESCE(p.TOTAL_PLANNED, 0) / NULLIF(d.TOTAL_DEMAND, 0) AS ACHIEVED_FILL_RATE,
       d.TOTAL_DEMAND, COALESCE(p.TOTAL_PLANNED, 0) AS TOTAL_PLANNED
FROM demand d
JOIN {ATOMIC}.DIM_CUSTOMER c ON d.CUSTOMER_ID = c.CUSTOMER_ID
LEFT JOIN production p ON d.CUSTOMER_ID = p.CUSTOMER_ID
ORDER BY (COALESCE(p.TOTAL_PLANNED, 0) / NULLIF(d.TOTAL_DEMAND, 0)) -
         d.SERVICE_LEVEL_TARGET_FILL_RATE ASC
"""

QUERY_FILL_RATE_BY_LINE = f"""
SELECT k.PLANT_NAME, k.LINE_CODE,
       SUM(k.TOTAL_PLANNED_QTY) / NULLIF(SUM(k.TOTAL_DEMAND_QTY), 0) AS FILL_RATE
FROM {DATA_MART}.FACT_SERVICE_AND_SCHEDULE_KPI k
WHERE k.SCENARIO_ID = '{{scenario}}'
GROUP BY k.PLANT_NAME, k.LINE_CODE
ORDER BY k.PLANT_NAME, k.LINE_CODE
"""

QUERY_CHANGEOVER_BY_PLANT = f"""
SELECT PLANT_NAME, LINE_CODE, MIN(CHANGEOVER_HOURS) AS CHANGEOVER_HOURS
FROM {DATA_MART}.FACT_SERVICE_AND_SCHEDULE_KPI
WHERE SCENARIO_ID = '{{scenario}}'
GROUP BY PLANT_NAME, LINE_CODE
ORDER BY PLANT_NAME, LINE_CODE
"""

QUERY_DEMAND_VS_PLANNED = f"""
SELECT PRODUCT_FAMILY,
       SUM(TOTAL_DEMAND_QTY) / COUNT(DISTINCT LINE_CODE) AS TOTAL_DEMAND_QTY,
       SUM(TOTAL_PLANNED_QTY) / COUNT(DISTINCT LINE_CODE) AS TOTAL_PLANNED_QTY
FROM {DATA_MART}.FACT_SERVICE_AND_SCHEDULE_KPI
WHERE SCENARIO_ID = '{{scenario}}'
GROUP BY PRODUCT_FAMILY
ORDER BY PRODUCT_FAMILY
"""

QUERY_DOS_BY_FAMILY = f"""
SELECT PRODUCT_FAMILY,
       AVG(INVENTORY_DAYS_OF_SUPPLY) AS AVG_DOS
FROM {DATA_MART}.FACT_SERVICE_AND_SCHEDULE_KPI
WHERE SCENARIO_ID = '{{scenario}}'
GROUP BY PRODUCT_FAMILY
ORDER BY PRODUCT_FAMILY
"""

QUERY_UTILIZATION_HEATMAP = f"""
SELECT l.LINE_CODE, DATE(s.TIME_SLOT_START) AS SLOT_DATE,
       COUNT(s.PRODUCT_ID) AS ASSIGNED_SLOTS,
       COUNT(DISTINCT c.LINE_CALENDAR_ID) AS TOTAL_SLOTS
FROM {DATA_MART}.FACT_LINE_SCHEDULE_OPTIMIZED s
JOIN {ATOMIC}.DIM_PRODUCTION_LINE l ON s.LINE_ID = l.LINE_ID
LEFT JOIN {ATOMIC}.FACT_LINE_CALENDAR c
    ON s.LINE_ID = c.LINE_ID AND DATE(s.TIME_SLOT_START) = DATE(c.TIME_SLOT_START)
    AND c.CALENDAR_STATUS = 'available'
WHERE s.SCENARIO_ID = '{{scenario}}'
GROUP BY l.LINE_CODE, DATE(s.TIME_SLOT_START)
ORDER BY l.LINE_CODE, SLOT_DATE
"""

QUERY_SCENARIO_PARAMS = f"""
SELECT * FROM {DATA_MART}.SCENARIO_PARAMETERS
WHERE SCENARIO_ID = '{{scenario}}'
"""

QUERY_PRODUCT_FAMILIES = f"""
SELECT DISTINCT PRODUCT_FAMILY FROM {ATOMIC}.DIM_PRODUCT ORDER BY PRODUCT_FAMILY
"""

QUERY_DEMAND_AGG = f"""
SELECT d.PRODUCT_ID, p.PRODUCT_FAMILY, SUM(d.FORECAST_QTY) AS FORECAST_QTY
FROM {ATOMIC}.FACT_DEMAND_FORECAST d
JOIN {ATOMIC}.DIM_PRODUCT p ON d.PRODUCT_ID = p.PRODUCT_ID
GROUP BY d.PRODUCT_ID, p.PRODUCT_FAMILY
ORDER BY p.PRODUCT_FAMILY
"""


def execute_query(session, sql, params=None):
    if params:
        for k, v in params.items():
            sql = sql.replace(f"{{{k}}}", str(v))
    return session.sql(sql).to_pandas()


@st.cache_data(ttl=300)
def cached_query(_session, sql, params=None):
    if params:
        for k, v in params.items():
            sql = sql.replace(f"{{{k}}}", str(v))
    return _session.sql(sql).to_pandas()
