------------------------------------------------------------------------
-- 01_setup.sql
-- Product Wheel Schedule Optimization - Database, Schemas, Tables
------------------------------------------------------------------------

USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS PRODUCT_WHEEL_SCHEDULE_OPTIMIZATION_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 120
    AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS PRODUCT_WHEEL_OPT;
DROP SCHEMA IF EXISTS PRODUCT_WHEEL_OPT.PUBLIC;

CREATE SCHEMA IF NOT EXISTS PRODUCT_WHEEL_OPT.RAW;
CREATE SCHEMA IF NOT EXISTS PRODUCT_WHEEL_OPT.ATOMIC;
CREATE SCHEMA IF NOT EXISTS PRODUCT_WHEEL_OPT.DATA_MART;

USE WAREHOUSE PRODUCT_WHEEL_SCHEDULE_OPTIMIZATION_WH;

CREATE STAGE IF NOT EXISTS PRODUCT_WHEEL_OPT.RAW.DATA_STAGE
    DIRECTORY = (ENABLE = TRUE);

------------------------------------------------------------------------
-- ATOMIC Dimension Tables
------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS PRODUCT_WHEEL_OPT.ATOMIC.DIM_PLANT (
    PLANT_ID            INTEGER NOT NULL PRIMARY KEY,
    PLANT_CODE          VARCHAR(20) NOT NULL,
    PLANT_NAME          VARCHAR(100) NOT NULL,
    TIMEZONE            VARCHAR(50),
    REGION              VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS PRODUCT_WHEEL_OPT.ATOMIC.DIM_PRODUCTION_LINE (
    LINE_ID                     INTEGER NOT NULL PRIMARY KEY,
    PLANT_ID                    INTEGER NOT NULL,
    LINE_CODE                   VARCHAR(20) NOT NULL,
    LINE_NAME                   VARCHAR(100) NOT NULL,
    LINE_TYPE                   VARCHAR(50),
    IS_ALLERGEN_DEDICATED_FLAG  BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (PLANT_ID) REFERENCES PRODUCT_WHEEL_OPT.ATOMIC.DIM_PLANT(PLANT_ID)
);

CREATE TABLE IF NOT EXISTS PRODUCT_WHEEL_OPT.ATOMIC.DIM_FORMULATION (
    FORMULATION_ID          INTEGER NOT NULL PRIMARY KEY,
    FORMULATION_CODE        VARCHAR(50) NOT NULL,
    FORMULATION_DESCRIPTION VARCHAR(500),
    ALLERGEN_CLASS          VARCHAR(100),
    PROCESSING_FAMILY       VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS PRODUCT_WHEEL_OPT.ATOMIC.DIM_CUSTOMER (
    CUSTOMER_ID      INTEGER NOT NULL PRIMARY KEY,
    CUSTOMER_CODE    VARCHAR(20) NOT NULL,
    CUSTOMER_NAME    VARCHAR(200) NOT NULL,
    CUSTOMER_SEGMENT VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS PRODUCT_WHEEL_OPT.ATOMIC.DIM_PRODUCT (
    PRODUCT_ID          INTEGER NOT NULL PRIMARY KEY,
    PRODUCT_CODE        VARCHAR(30) NOT NULL,
    PRODUCT_DESCRIPTION VARCHAR(500),
    FORMULATION_ID      INTEGER NOT NULL,
    BRAND_ID            INTEGER,
    PACKAGE_SIZE_UOM    VARCHAR(30),
    SHELF_LIFE_DAYS     INTEGER,
    PRODUCT_FAMILY      VARCHAR(100),
    FOREIGN KEY (FORMULATION_ID) REFERENCES PRODUCT_WHEEL_OPT.ATOMIC.DIM_FORMULATION(FORMULATION_ID)
);

CREATE TABLE IF NOT EXISTS PRODUCT_WHEEL_OPT.ATOMIC.DIM_FORMULATION_COMPONENT (
    FORMULATION_COMPONENT_ID INTEGER NOT NULL PRIMARY KEY,
    FORMULATION_ID           INTEGER NOT NULL,
    COMPONENT_ID             INTEGER,
    COMPONENT_SEQ            INTEGER,
    COMPONENT_NAME           VARCHAR(200),
    QUANTITY_PER_BATCH       FLOAT,
    UOM                      VARCHAR(20),
    FOREIGN KEY (FORMULATION_ID) REFERENCES PRODUCT_WHEEL_OPT.ATOMIC.DIM_FORMULATION(FORMULATION_ID)
);

------------------------------------------------------------------------
-- ATOMIC Fact Tables
------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS PRODUCT_WHEEL_OPT.ATOMIC.FACT_CONTRACT (
    CONTRACT_ID                    INTEGER NOT NULL PRIMARY KEY,
    CUSTOMER_ID                    INTEGER NOT NULL,
    CONTRACT_START_DATE            DATE NOT NULL,
    CONTRACT_END_DATE              DATE NOT NULL,
    SERVICE_LEVEL_TARGET_FILL_RATE FLOAT,
    MAX_DAYS_OF_SUPPLY_TARGET      INTEGER,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES PRODUCT_WHEEL_OPT.ATOMIC.DIM_CUSTOMER(CUSTOMER_ID)
);

CREATE TABLE IF NOT EXISTS PRODUCT_WHEEL_OPT.ATOMIC.FACT_CONTRACT_ITEM (
    CONTRACT_ITEM_ID   INTEGER NOT NULL PRIMARY KEY,
    CONTRACT_ID        INTEGER NOT NULL,
    PRODUCT_ID         INTEGER NOT NULL,
    MIN_ANNUAL_VOLUME  INTEGER,
    MAX_ANNUAL_VOLUME  INTEGER,
    AGREED_PRICE_PER_UNIT FLOAT,
    PRIORITY_TIER      INTEGER,
    FOREIGN KEY (CONTRACT_ID) REFERENCES PRODUCT_WHEEL_OPT.ATOMIC.FACT_CONTRACT(CONTRACT_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT_WHEEL_OPT.ATOMIC.DIM_PRODUCT(PRODUCT_ID)
);

CREATE TABLE IF NOT EXISTS PRODUCT_WHEEL_OPT.ATOMIC.FACT_DEMAND_FORECAST (
    FORECAST_ID          INTEGER NOT NULL PRIMARY KEY,
    CUSTOMER_ID          INTEGER NOT NULL,
    PRODUCT_ID           INTEGER NOT NULL,
    FORECAST_WEEK_START  DATE NOT NULL,
    FORECAST_WEEK_END    DATE NOT NULL,
    FORECAST_QTY         FLOAT NOT NULL,
    FORECAST_VERSION     VARCHAR(20),
    SOURCE_SYSTEM        VARCHAR(50),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES PRODUCT_WHEEL_OPT.ATOMIC.DIM_CUSTOMER(CUSTOMER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT_WHEEL_OPT.ATOMIC.DIM_PRODUCT(PRODUCT_ID)
);

CREATE TABLE IF NOT EXISTS PRODUCT_WHEEL_OPT.ATOMIC.FACT_LINE_CALENDAR (
    LINE_CALENDAR_ID  INTEGER NOT NULL PRIMARY KEY,
    LINE_ID           INTEGER NOT NULL,
    TIME_SLOT_START   TIMESTAMP_NTZ NOT NULL,
    TIME_SLOT_END     TIMESTAMP_NTZ NOT NULL,
    AVAILABLE_HOURS   FLOAT NOT NULL,
    CALENDAR_STATUS   VARCHAR(20) DEFAULT 'available',
    FOREIGN KEY (LINE_ID) REFERENCES PRODUCT_WHEEL_OPT.ATOMIC.DIM_PRODUCTION_LINE(LINE_ID)
);

CREATE TABLE IF NOT EXISTS PRODUCT_WHEEL_OPT.ATOMIC.FACT_LINE_PRODUCT_THROUGHPUT (
    LINE_PRODUCT_ID         INTEGER NOT NULL PRIMARY KEY,
    LINE_ID                 INTEGER NOT NULL,
    PRODUCT_ID              INTEGER NOT NULL,
    RUN_RATE_UNITS_PER_HOUR FLOAT NOT NULL,
    MIN_RUN_HOURS_PER_CAMPAIGN FLOAT,
    MAX_RUN_HOURS_PER_SLOT  FLOAT,
    FOREIGN KEY (LINE_ID) REFERENCES PRODUCT_WHEEL_OPT.ATOMIC.DIM_PRODUCTION_LINE(LINE_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT_WHEEL_OPT.ATOMIC.DIM_PRODUCT(PRODUCT_ID)
);

CREATE TABLE IF NOT EXISTS PRODUCT_WHEEL_OPT.ATOMIC.FACT_LINE_PRODUCT_CHANGEOVER (
    CHANGEOVER_ID         INTEGER NOT NULL PRIMARY KEY,
    LINE_ID               INTEGER NOT NULL,
    FROM_PRODUCT_ID       INTEGER NOT NULL,
    TO_PRODUCT_ID         INTEGER NOT NULL,
    CHANGEOVER_TIME_HOURS FLOAT NOT NULL,
    CHANGEOVER_COST       FLOAT,
    FOREIGN KEY (LINE_ID) REFERENCES PRODUCT_WHEEL_OPT.ATOMIC.DIM_PRODUCTION_LINE(LINE_ID),
    FOREIGN KEY (FROM_PRODUCT_ID) REFERENCES PRODUCT_WHEEL_OPT.ATOMIC.DIM_PRODUCT(PRODUCT_ID),
    FOREIGN KEY (TO_PRODUCT_ID) REFERENCES PRODUCT_WHEEL_OPT.ATOMIC.DIM_PRODUCT(PRODUCT_ID)
);

CREATE TABLE IF NOT EXISTS PRODUCT_WHEEL_OPT.ATOMIC.FACT_INVENTORY_POSITION (
    INVENTORY_SNAPSHOT_ID INTEGER NOT NULL PRIMARY KEY,
    PRODUCT_ID            INTEGER NOT NULL,
    PLANT_ID              INTEGER NOT NULL,
    SNAPSHOT_TIMESTAMP    TIMESTAMP_NTZ NOT NULL,
    ON_HAND_QTY           FLOAT NOT NULL,
    ON_ORDER_QTY          FLOAT DEFAULT 0,
    SAFETY_STOCK_QTY      FLOAT DEFAULT 0,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT_WHEEL_OPT.ATOMIC.DIM_PRODUCT(PRODUCT_ID),
    FOREIGN KEY (PLANT_ID) REFERENCES PRODUCT_WHEEL_OPT.ATOMIC.DIM_PLANT(PLANT_ID)
);

CREATE TABLE IF NOT EXISTS PRODUCT_WHEEL_OPT.ATOMIC.FACT_PRODUCTION_ORDER (
    PROD_ORDER_ID    INTEGER NOT NULL PRIMARY KEY,
    PLANT_ID         INTEGER NOT NULL,
    LINE_ID          INTEGER NOT NULL,
    PRODUCT_ID       INTEGER NOT NULL,
    PLANNED_START_TIME TIMESTAMP_NTZ NOT NULL,
    PLANNED_END_TIME   TIMESTAMP_NTZ NOT NULL,
    PLANNED_QTY      FLOAT NOT NULL,
    ORDER_STATUS     VARCHAR(20) DEFAULT 'planned',
    SOURCE_SYSTEM    VARCHAR(50),
    FOREIGN KEY (PLANT_ID) REFERENCES PRODUCT_WHEEL_OPT.ATOMIC.DIM_PLANT(PLANT_ID),
    FOREIGN KEY (LINE_ID) REFERENCES PRODUCT_WHEEL_OPT.ATOMIC.DIM_PRODUCTION_LINE(LINE_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT_WHEEL_OPT.ATOMIC.DIM_PRODUCT(PRODUCT_ID)
);

CREATE TABLE IF NOT EXISTS PRODUCT_WHEEL_OPT.ATOMIC.FACT_PRODUCTION_EVENT (
    PRODUCTION_EVENT_ID INTEGER NOT NULL PRIMARY KEY,
    PROD_ORDER_ID       INTEGER NOT NULL,
    LINE_ID             INTEGER NOT NULL,
    PRODUCT_ID          INTEGER NOT NULL,
    EVENT_START_TIME    TIMESTAMP_NTZ NOT NULL,
    EVENT_END_TIME      TIMESTAMP_NTZ NOT NULL,
    ACTUAL_QTY          FLOAT NOT NULL,
    SCRAP_QTY           FLOAT DEFAULT 0,
    FOREIGN KEY (PROD_ORDER_ID) REFERENCES PRODUCT_WHEEL_OPT.ATOMIC.FACT_PRODUCTION_ORDER(PROD_ORDER_ID),
    FOREIGN KEY (LINE_ID) REFERENCES PRODUCT_WHEEL_OPT.ATOMIC.DIM_PRODUCTION_LINE(LINE_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT_WHEEL_OPT.ATOMIC.DIM_PRODUCT(PRODUCT_ID)
);

CREATE TABLE IF NOT EXISTS PRODUCT_WHEEL_OPT.ATOMIC.FACT_PRODUCT_COSTING (
    PRODUCT_COST_ID        INTEGER NOT NULL PRIMARY KEY,
    PRODUCT_ID             INTEGER NOT NULL,
    COST_VERSION           VARCHAR(20) NOT NULL,
    PLANT_ID               INTEGER,
    MATERIAL_COST_PER_UNIT FLOAT,
    CONVERSION_COST_PER_UNIT FLOAT,
    PACKAGING_COST_PER_UNIT  FLOAT,
    OVERHEAD_COST_PER_UNIT   FLOAT,
    STANDARD_MARGIN_PER_UNIT FLOAT,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT_WHEEL_OPT.ATOMIC.DIM_PRODUCT(PRODUCT_ID)
);

------------------------------------------------------------------------
-- DATA_MART Output Tables
------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS PRODUCT_WHEEL_OPT.DATA_MART.FACT_DEMAND_FORECAST_ENRICHED (
    CUSTOMER_ID              INTEGER NOT NULL,
    PRODUCT_ID               INTEGER NOT NULL,
    WEEK_START               DATE NOT NULL,
    WEEK_END                 DATE NOT NULL,
    FORECAST_QTY             FLOAT NOT NULL,
    PREDICTION_INTERVAL_LOW  FLOAT,
    PREDICTION_INTERVAL_HIGH FLOAT,
    MODEL_VERSION            VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS PRODUCT_WHEEL_OPT.DATA_MART.FACT_LINE_SCHEDULE_OPTIMIZED (
    SCENARIO_ID                VARCHAR(50) NOT NULL,
    LINE_ID                    INTEGER NOT NULL,
    TIME_SLOT_START            TIMESTAMP_NTZ NOT NULL,
    TIME_SLOT_END              TIMESTAMP_NTZ NOT NULL,
    PRODUCT_ID                 INTEGER NOT NULL,
    PLANNED_QTY                FLOAT,
    PROJECTED_FILL_RATE        FLOAT,
    PROJECTED_INVENTORY_QTY    FLOAT,
    TOTAL_CHANGEOVER_TIME_HOURS FLOAT,
    OBJECTIVE_COST             FLOAT
);

CREATE TABLE IF NOT EXISTS PRODUCT_WHEEL_OPT.DATA_MART.FACT_SERVICE_AND_SCHEDULE_KPI (
    KPI_ID                  INTEGER AUTOINCREMENT,
    SCENARIO_ID             VARCHAR(50),
    PLANT_NAME              VARCHAR(100),
    LINE_CODE               VARCHAR(20),
    PRODUCT_FAMILY          VARCHAR(100),
    CUSTOMER_NAME           VARCHAR(200),
    WEEK_START              DATE,
    FILL_RATE               FLOAT,
    INVENTORY_DAYS_OF_SUPPLY FLOAT,
    CHANGEOVER_HOURS        FLOAT,
    TOTAL_PLANNED_QTY       FLOAT,
    TOTAL_DEMAND_QTY        FLOAT,
    OBJECTIVE_COST          FLOAT
);

------------------------------------------------------------------------
-- DATA_MART Scenario Management Tables
------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS PRODUCT_WHEEL_OPT.DATA_MART.SCENARIO_PARAMETERS (
    SCENARIO_ID             VARCHAR(50) NOT NULL,
    CREATED_AT              TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY              VARCHAR(100) DEFAULT CURRENT_USER(),
    HORIZON_DAYS            INTEGER,
    SHIFTS_PER_DAY          INTEGER,
    TIME_LIMIT_SEC          INTEGER,
    MIP_GAP_PCT             FLOAT,
    INV_COST_MULTIPLIER     FLOAT,
    BO_COST_MULTIPLIER      FLOAT,
    CO_COST_MULTIPLIER      FLOAT,
    DEMAND_MULTIPLIER       FLOAT,
    DEMAND_SHOCK_FAMILY     VARCHAR(100),
    DEMAND_SHOCK_PCT        FLOAT,
    INV_MULTIPLIER          FLOAT,
    PLANT_FILTER            VARCHAR(500),
    LINE_FILTER             VARCHAR(500),
    MAX_PRODUCTS_PER_LINE   INTEGER,
    SOLVER_ENGINE           VARCHAR(50),
    SOLVE_TIME_SEC          FLOAT,
    TOTAL_OBJECTIVE_COST    FLOAT,
    STATUS                  VARCHAR(20)
);

CREATE OR REPLACE VIEW PRODUCT_WHEEL_OPT.DATA_MART.SCENARIO_COMPARISON AS
SELECT
    k.SCENARIO_ID,
    sp.CREATED_AT,
    sp.HORIZON_DAYS,
    sp.DEMAND_MULTIPLIER,
    sp.INV_COST_MULTIPLIER,
    sp.BO_COST_MULTIPLIER,
    sp.CO_COST_MULTIPLIER,
    SUM(k.TOTAL_PLANNED_QTY) / NULLIF(SUM(k.TOTAL_DEMAND_QTY), 0) AS OVERALL_FILL_RATE,
    SUM(k.CHANGEOVER_HOURS) AS TOTAL_CHANGEOVER_HOURS,
    AVG(k.INVENTORY_DAYS_OF_SUPPLY) AS AVG_DAYS_OF_SUPPLY,
    SUM(k.OBJECTIVE_COST) AS TOTAL_OBJECTIVE_COST,
    COUNT(DISTINCT k.LINE_CODE) AS LINES_SOLVED
FROM PRODUCT_WHEEL_OPT.DATA_MART.FACT_SERVICE_AND_SCHEDULE_KPI k
LEFT JOIN PRODUCT_WHEEL_OPT.DATA_MART.SCENARIO_PARAMETERS sp ON k.SCENARIO_ID = sp.SCENARIO_ID
GROUP BY k.SCENARIO_ID, sp.CREATED_AT, sp.HORIZON_DAYS,
         sp.DEMAND_MULTIPLIER, sp.INV_COST_MULTIPLIER,
         sp.BO_COST_MULTIPLIER, sp.CO_COST_MULTIPLIER;
