/*
  07_semantic_views.sql
  Creates stage for semantic models and deploys 5 Semantic Views for Cortex Analyst.
*/

USE DATABASE PRODUCT_WHEEL_OPT;
USE SCHEMA RAW;
USE WAREHOUSE PRODUCT_WHEEL_SCHEDULE_OPTIMIZATION_WH;

CREATE STAGE IF NOT EXISTS SEMANTIC_MODELS
  DIRECTORY = (ENABLE = TRUE)
  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

-- Upload YAML files to stage (done by deploy.sh via PUT or snow stage copy)
-- PUT file:///path/to/semantic_models/*.yaml @SEMANTIC_MODELS AUTO_COMPRESS=FALSE;

-- Create Semantic Views from YAML files
USE SCHEMA DATA_MART;

CREATE OR REPLACE SEMANTIC VIEW SCHEDULE_ANALYST_VIEW
  FROM @PRODUCT_WHEEL_OPT.RAW.SEMANTIC_MODELS/schedule_analyst.yaml;

CREATE OR REPLACE SEMANTIC VIEW DEMAND_ANALYST_VIEW
  FROM @PRODUCT_WHEEL_OPT.RAW.SEMANTIC_MODELS/demand_analyst.yaml;

CREATE OR REPLACE SEMANTIC VIEW INVENTORY_ANALYST_VIEW
  FROM @PRODUCT_WHEEL_OPT.RAW.SEMANTIC_MODELS/inventory_analyst.yaml;

CREATE OR REPLACE SEMANTIC VIEW CONTRACT_ANALYST_VIEW
  FROM @PRODUCT_WHEEL_OPT.RAW.SEMANTIC_MODELS/contract_analyst.yaml;

CREATE OR REPLACE SEMANTIC VIEW CHANGEOVER_ANALYST_VIEW
  FROM @PRODUCT_WHEEL_OPT.RAW.SEMANTIC_MODELS/changeover_analyst.yaml;

-- Grant access
GRANT USAGE ON SEMANTIC VIEW SCHEDULE_ANALYST_VIEW TO ROLE PUBLIC;
GRANT USAGE ON SEMANTIC VIEW DEMAND_ANALYST_VIEW TO ROLE PUBLIC;
GRANT USAGE ON SEMANTIC VIEW INVENTORY_ANALYST_VIEW TO ROLE PUBLIC;
GRANT USAGE ON SEMANTIC VIEW CONTRACT_ANALYST_VIEW TO ROLE PUBLIC;
GRANT USAGE ON SEMANTIC VIEW CHANGEOVER_ANALYST_VIEW TO ROLE PUBLIC;
