/*
  08_notes.sql
  Creates USER_NOTES table and SAVE_USER_NOTE UDF for the Cortex Agent.
*/

USE DATABASE PRODUCT_WHEEL_OPT;
USE SCHEMA DATA_MART;
USE WAREHOUSE PRODUCT_WHEEL_SCHEDULE_OPTIMIZATION_WH;

CREATE TABLE IF NOT EXISTS USER_NOTES (
    NOTE_ID         NUMBER AUTOINCREMENT PRIMARY KEY,
    CREATED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY      VARCHAR DEFAULT CURRENT_USER(),
    PAGE_CONTEXT    VARCHAR,
    ENTITY_TYPE     VARCHAR,
    ENTITY_ID       VARCHAR,
    NOTE_TEXT       VARCHAR(4000),
    NOTE_TYPE       VARCHAR DEFAULT 'comment',
    IS_RESOLVED     BOOLEAN DEFAULT FALSE,
    RESOLVED_AT     TIMESTAMP_NTZ,
    RESOLVED_BY     VARCHAR
);

CREATE OR REPLACE FUNCTION SAVE_USER_NOTE(
    page_context VARCHAR,
    entity_type VARCHAR,
    entity_id VARCHAR,
    note_text VARCHAR,
    note_type VARCHAR
)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN
  INSERT INTO PRODUCT_WHEEL_OPT.DATA_MART.USER_NOTES
    (PAGE_CONTEXT, ENTITY_TYPE, ENTITY_ID, NOTE_TEXT, NOTE_TYPE)
  VALUES
    (page_context, entity_type, entity_id, note_text, note_type);
  RETURN 'Note saved successfully: "' || LEFT(note_text, 50) || '"';
END
$$;

GRANT SELECT, INSERT, UPDATE ON TABLE USER_NOTES TO ROLE PUBLIC;
GRANT USAGE ON FUNCTION SAVE_USER_NOTE(VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR) TO ROLE PUBLIC;
